source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.7'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Gem to store and help users sign in and out
gem 'devise', '~> 3.4.1'
# Jquery gem to handle nested forms. For example a project with tasks/invoices
gem 'cocoon', '~> 1.2.6'
# upload management for active record
gem 'paperclip', '~> 4.2.1'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby
gem 'haml', '~>4.0.6'
gem 'simple_form', '~>3.1.0'
gem 'bootstrap-sass', '3.3.1.0'
# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'spring',        group: :development



