# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 842b1f460cfeb12e88e4411d27cb37bb10f711596ffeb94365e6cb889af437889f5075d1186bfb68f6bc63e56f1006d2c728594d4c23b81dc108c6511547e92f

test:
  secret_key_base: bbcde721127c8c7da80d493da8d6ff81c7d9e67bfd49c25eb7ce66a71d7d866e59302c3ba9d8a1c87d7b99a3c7a4b200f8a2b814e72e10a17c7d5519ca91e62b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
